name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["open"]
assignees:
  - uhhhuser
type: bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give a precise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour?
      description: What did you expect to happen?
      placeholder: Tell us what was supposed to happen!
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour?
      description: If necessary, expand on what actually happend.
      placeholder: What really happened? 
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      value: |
        1. 
        2. 
        3. 
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform did this bug occur on?
      multiple: true
        - Windows 10
        - Windows 11
        - IOS
        - Android
        - MacOS
        - Linux
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Zen
        - Vivaldi
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
